AcademyEF/AcademyEF/Controllers/CoursesController.cs
using AcademyEF.Models;
using AcademyEF.Services;
using AcademyEF.ViewModels.CoursesVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using AcademyEF.Filters;
using AcademyEF.Repositories;

namespace AcademyEF.Controllers
{
    public class CoursesController : Controller
    {
        public CoursesService coursesService { get; set; }

        public CoursesController()
        {
            coursesService = new CoursesService();
        }
        
        public ActionResult List()
        {
            List<Course> courses = coursesService.GetAll();
            CourseListVM courseListVM = new CourseListVM();
            courseListVM.Courses = courses;

            return View(courseListVM);
        }

        [AuthenticationFilter]
        public ActionResult MyCourses()
        {
            List<Course> courses = coursesService.GetMyCourses(AuthenticationService.LoggedUser.ID);
            CourseListVM courseListVM = new CourseListVM();
            courseListVM.Courses = courses;

            return View("List",courseListVM);
        } 

        [AuthenticationFilter]
        [AuthorizationFilter]
        public ActionResult Details(int id)
        {
            return View();
        }

        [AuthenticationFilter]
        [AuthorizationFilter]
        public ActionResult Edit(int? id)
        {
            EditVM model = new EditVM();
            Course course;
            if (id.HasValue)
            {
                course = coursesService.GetByID(id.Value);
                if (course == null)
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                course = new Course();
            }
            model.Name = course.Name;
            model.Description = course.Description;
            model.ImagePath = course.ImagePath;
            model.ID = course.ID;
            return View(model);
        }

        [AuthenticationFilter]
        [AuthorizationFilter]
        [HttpPost]
        public ActionResult Edit()
        {
            EditVM model = new EditVM();
            TryUpdateModel(model);
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Course course;
            if (model.ID != 0)
            {
                course = coursesService.GetByID(model.ID);
            }
            else
            {
                course = new Course();
            }

            //if (model.ImageUpload != null && model.ImageUpload.ContentLength > 0)
            //{
            //    var file = Path.GetExtension(model.ImageUpload.FileName);
            //    if (String.IsNullOrEmpty(file) || !file.Equals(".jpg", StringComparison.OrdinalIgnoreCase))
            //    {
            //        ModelState.AddModelError("", "Image format not accepted");
            //    }
            //    else
            //    {
            //        if (!String.IsNullOrEmpty(model.ImagePath))
            //        {
            //            var imagePathOld = Path.Combine(Server.MapPath("/Uploads/"), model.ImagePath);
            //            System.IO.File.Delete(imagePathOld);
            //        }
            //        var uploadDir = "/Uploads/";
            //        var imagePath = Path.Combine(Server.MapPath(uploadDir), model.ImageUpload.FileName);
            //        model.ImagePath = model.ImageUpload.FileName;
            //        model.ImageUpload.SaveAs(imagePath);
            //    }
            //}

            if (course == null)
            {
                return RedirectToAction("List");
            }
            course.ID = model.ID;
            course.Name = model.Name;
            course.Description = model.Description;
            course.ImagePath = model.ImagePath;
            coursesService.Save(course);
            return RedirectToAction("List");
        }

        [AuthenticationFilter]
        [AuthorizationFilter]
        public ActionResult Delete(int? id)
        {

            if (id.HasValue)
            {
                Course course = coursesService.GetByID(id.Value);
                //var imagePath = Path.Combine(Server.MapPath("/Uploads/"), course.ImagePath);
                //System.IO.File.Delete(imagePath);
                coursesService.Delete(id.Value);
            }
            return RedirectToAction("List");
        }

        [AuthenticationFilter]
        public ActionResult Assign(int? id)
        {
            if (id.HasValue)
            {
                UnitOfWork unit = new UnitOfWork();
                coursesService = new CoursesService(unit);
                UsersService userService = new UsersService(unit);

                var user = userService.GetByID(AuthenticationService.LoggedUser.ID);
                Course course = coursesService.GetByID(id.Value);

                course.Users.Add(user);

                coursesService.Save(course);
            }

            return RedirectToAction("List");
        }
    }
}

AcademyEF/AcademyEF/Views/Courses/Edit.cshtml
@model AcademyEF.ViewModels.CoursesVM.EditVM

@{
    if (Model.ID == 0)
    {
        ViewBag.Title = "Add new course";
    }
    else
    {
        ViewBag.Title = "Edit new course";
    }
}

@using (Html.BeginForm("Edit", "Courses", null, FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.ID)
        @*@Html.HiddenFor(model => model.ImagePath)*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUpload,"Image URL:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

AcademyEF/AcademyEF/Views/Courses/List.cshtml
@model AcademyEF.ViewModels.CoursesVM.CourseListVM

@{
    ViewBag.Title = "Courses";
    ViewBag.Description = "Our current courses";
}
@if (AcademyEF.Services.AuthenticationService.LoggedUser != null &&
    AcademyEF.Services.AuthenticationService.LoggedUser.IsAdmin)
{
    <p class="row" style="margin-left:17px;">
        @Html.ActionLink("Create New", "Edit", null, new { @class = "btn btn-info" })
    </p>
}
@if (Model.Courses.Count == 0)
{
    <p>No courses found !!!</p>
}
else
{
    foreach (var item in Model.Courses)
    {
        <div class="col-md-4">
            <div class="card" style="width: 30rem;">
                <img class="card-img-top" src="@item.ImagePath" alt="Card image cap" style="width:300px;height:300px;">
                <div class="card-block">
                    <h4 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h4>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    @if (AcademyEF.Services.AuthenticationService.LoggedUser != null &&
                            AcademyEF.Services.AuthenticationService.LoggedUser.IsAdmin)
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-primary" }) @Html.Raw("&nbsp;")
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                    }

                    @if (AcademyEF.Services.AuthenticationService.LoggedUser != null &&
                        !AcademyEF.Services.AuthenticationService.LoggedUser.Courses.Select(c=>c.ID).Contains(item.ID))
                    {
                    @Html.ActionLink("Assign", "Assign", new { id = item.ID }, new { @class = "btn btn-success" })
                    }
                </div>
            </div>
        </div>
    }
}